<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="2" failures="0" skipped="0" tests="2" time="0.184" timestamp="2024-04-20T14:13:07.628029" hostname="MacBook-Pro-de-Guilherme.local"><testcase classname="" name="authorizers.jwt.main" time="0.000"><error message="collection failure">ImportError while importing test module '/Users/guialves/personal_projects/lforge/lambda-forge-sandbox/authorizers/jwt/main.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../.pyenv/versions/3.9.7/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
authorizers/jwt/main.py:2: in &lt;module&gt;
    import jwt
E   ModuleNotFoundError: No module named 'jwt'</error></testcase><testcase classname="" name="functions.auth.signin.main" time="0.000"><error message="collection failure">ImportError while importing test module '/Users/guialves/personal_projects/lforge/lambda-forge-sandbox/functions/auth/signin/main.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../.pyenv/versions/3.9.7/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
functions/auth/signin/main.py:6: in &lt;module&gt;
    import jwt
E   ModuleNotFoundError: No module named 'jwt'</error></testcase></testsuite></testsuites>